name: angular_pagination_example
version: 0.2.0
author: Egor Day <edaydev@gmail.com>
description: Example for angular_pagination
homepage: https://github.com/daydev/angular_pagination.git
dependencies:
  angular: any
  angular_pagination:
    path: ..
  browser: any
  shadow_dom: any
transformers:
- angular