name: angular_pagination
version: 0.1.2
author: Egor Day <edaydev@gmail.com>
description: Pagination module for angular.dart
homepage: https://github.com/daydev/angular_pagination.git
dependencies:
  angular: any
dev_dependencies:
  browser: any
  hop: any
  unittest: any